name: Test Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
      - run: flutter doctor -v
      - run: flutter pub get
      - run: |
            cd example
            flutter build -v apk --debug --split-per-abi
      - run: |
          cd example
          flutter build -v ios --debug --no-codesign